// Code generated by cmd/gencode; DO NOT EDIT.
package testa

import (
	"blogtest/internal/selector/common"
	"blogtest/internal/selector/registry"
)

func init() {
	registry.Register([]common.SelectorGroup{
		TypeCheckSelector,
	})
}
